# Generated by Django 5.1.4 on 2024-12-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='max_participants',
            field=models.PositiveIntegerField(default=0, help_text='Максимальное количество участников'),
        ),
    ]
