# Generated by Django 5.1.4 on 2024-12-06 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_answer_survey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='max_participants',
        ),
    ]
