# Generated by Django 5.1.3 on 2024-12-02 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='poll',
            new_name='survey',
        ),
    ]
